# Generated by Django 6.0 on 2026-02-10 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('department', 'Department'), ('nss', 'NSS'), ('ncc', 'NCC'), ('union', 'Union'), ('other', 'Other')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('participation_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed')], max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venue', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('principal_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
