# Generated by Django 6.0 on 2026-02-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_file',
            field=models.FileField(blank=True, null=True, upload_to='attendance/'),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='report_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
