# Generated by Django 6.0.2 on 2026-03-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_photo_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chief_guest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
