# Generated by Django 6.0.2 on 2026-03-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tag_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
