# Generated by Django 6.0.2 on 2026-04-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_tag_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
