# Generated by Django 6.0.2 on 2026-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submitted', 'Event Submitted'), ('approved', 'Event Approved'), ('rejected', 'Event Rejected'), ('cancel_requested', 'Cancellation Requested'), ('cancel_approved', 'Cancellation Approved'), ('cancel_rejected', 'Cancellation Rejected'), ('completed', 'Event Completed'), ('venue_changed', 'Venue Changed'), ('reminder', 'Reminder')], max_length=30),
        ),
    ]
